apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: null
  name: whshare-cleanup
spec:
  schedule: '* 0 * * *'
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 0
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: whshare-cleanup
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: jojii/wh-share:v1.4.2
            name: wh-share
            volumeMounts:
            - name: config
              mountPath: /app/data/
            env:
            - name: S_CONFIG
              value: /app/data/config
            - name: S_LOG_LEVEL
              value: debug
            - name: S_CLEAN
              value: "true"
            resources: {}
          restartPolicy: Never
          volumes:
          - name: config
            configMap:
              name: whshareconfig
status: {}
